import { makeStyles } from '@fluentui/react-components';

export const useCompanyMapViewerStyles = makeStyles({
  mapContainer: {
    height: '400px',
    width: '100%',
    borderRadius: '8px',
    position: 'relative',
  },
  pinnedAddressCard: {
    backgroundColor: '#e6f7ff',
    border: '2px solid #1890ff',
    borderRadius: '8px',
    padding: '16px',
    marginBottom: '16px',
    boxShadow: '0 2px 8px rgba(0, 0, 0, 0.1)',
    position: 'relative',
  },
  pinnedAddressHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    marginBottom: '8px',
    color: '#1890ff',
    fontWeight: '600',
    fontSize: '14px',
  },
  pinnedAddressText: {
    fontSize: '14px',
    color: '#333',
    lineHeight: '1.4',
  },
  pinnedAddressCloseButton: {
    position: 'absolute',
    top: '8px',
    right: '8px',
    background: 'transparent',
    border: 'none',
    cursor: 'pointer',
    color: '#1890ff',
    padding: '2px',
    borderRadius: '4px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    '&:hover': {
      backgroundColor: '#f0f0f0',
    },
  },
  mapInstructions: {
    position: 'absolute',
    top: '10px',
    left: '10px',
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    color: '#333',
    padding: '8px 12px',
    borderRadius: '6px',
    fontSize: '12px',
    zIndex: 1000,
    border: '1px solid #ddd',
    boxShadow: '0 2px 4px rgba(0, 0, 0, 0.1)',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  mapInstructionsCloseButton: {
    background: 'transparent',
    border: 'none',
    cursor: 'pointer',
    color: '#666',
    padding: '2px',
    borderRadius: '4px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 'auto',
    '&:hover': {
      backgroundColor: 'rgba(102, 102, 102, 0.1)',
    },
  },
  addressNotFoundOverlay: {
    position: 'absolute',
    top: '50px',
    left: '50%',
    transform: 'translateX(-50%)',
    backgroundColor: 'rgba(255, 193, 7, 0.95)',
    color: '#856404',
    padding: '12px 16px',
    borderRadius: '8px',
    fontSize: '14px',
    fontWeight: '600',
    zIndex: 1000,
    border: '2px solid #ffc107',
    boxShadow: '0 4px 8px rgba(0, 0, 0, 0.15)',
    maxWidth: '90%',
    textAlign: 'center',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  addressNotFoundCloseButton: {
    background: 'transparent',
    border: 'none',
    cursor: 'pointer',
    color: '#856404',
    padding: '2px',
    borderRadius: '4px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 'auto',
    '&:hover': {
      backgroundColor: 'rgba(133, 100, 4, 0.1)',
    },
  },
  mapFooterActionButtons: {
    gap: '8px',
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between'
  },
  usePinnedAddressButton: {
    flex: '1 1 auto',
    minWidth: 'fit-content'
  },
  closeMapButton: {
    flex: '1 1 auto',
    minWidth: 'fit-content'
  }
});
